USE emoldino;

DROP TABLE IF EXISTS MMS_QUEUE;
DROP TABLE IF EXISTS DATA_QUEUE;
DROP TABLE IF EXISTS SENSOR_HISTORY;
DROP TABLE IF EXISTS COMMAND_CACHE;
DROP TABLE IF EXISTS COMMAND_COMP_CACHE;

CREATE TABLE DATA_QUEUE(
   ID BIGINT NOT NULL AUTO_INCREMENT,   
   DEVICE_ID VARCHAR (256) DEFAULT NULL,
   DEVICE_TYPE VARCHAR (256) DEFAULT NULL,		
   DEVICE_SW_VERSION VARCHAR (256) DEFAULT NULL,		
   DEVICE_TIME VARCHAR (256) DEFAULT NULL,		
   DATA_TYPE VARCHAR (256) DEFAULT NULL,							   
   DATA  LONGTEXT DEFAULT NULL,    
   CREATED_AT DATETIME NULL DEFAULT NULL,   
   PRIMARY KEY (ID) USING BTREE
)CHARSET=UTF8MB4;

CREATE TABLE SENSOR_HISTORY(
   ID BIGINT NOT NULL AUTO_INCREMENT,
   DEVICE_ID VARCHAR (256) DEFAULT NULL,
   DEVICE_TYPE VARCHAR (256) DEFAULT NULL,
   DEVICE_SW_VERSION VARCHAR (256) DEFAULT NULL,		
   LAST_COMM_TIME DATETIME NULL DEFAULT NULL,
   CUMUL_NUM BIGINT NULL DEFAULT NULL,
   CREATED_AT DATETIME NULL DEFAULT NULL,   
   UPDATED_AT DATETIME NULL DEFAULT NULL,
   PRIMARY KEY (ID) USING BTREE,
   UNIQUE INDEX UX_SENHIS (DEVICE_ID) USING BTREE
)CHARSET=UTF8MB4;

CREATE TABLE COMMAND_CACHE(
   ID BIGINT NOT NULL AUTO_INCREMENT,	
   DEVICE_ID VARCHAR (256) DEFAULT NULL,
   COMMAND VARCHAR (256) DEFAULT NULL,
   INDEX_NO INT NULL DEFAULT NULL,
   DATA LONGTEXT NULL DEFAULT NULL, 
   PRIMARY KEY (ID) USING BTREE
)CHARSET=UTF8MB4;

CREATE TABLE COMMAND_COMP_CACHE(
   ID BIGINT NOT NULL AUTO_INCREMENT,	
   DEVICE_ID VARCHAR (256) NOT NULL,
   LAST_INDEX_NO INT NOT NULL,
   PRIMARY KEY (ID) USING BTREE,
   UNIQUE INDEX UX_CMD_COMPCACHE (DEVICE_ID) USING BTREE
)CHARSET=UTF8MB4;
